Refactor Map Guide.
canopy-iiif/docs pull request #19
Opened 2023-11-30 17:42 UTC by markpbaggett

# What Does This Do

This addresses [Issue-11](https://github.com/canopy-iiif/docs/issues/11) and refactors the enable a map guide to follow the pattern of the other guides written thus far.

# How To Test

Pull down the branch and visit http://localhost:3000/docs/enable-a-map-with-navPlace

2023-11-30 20:59 UTC, adamjarling approved these changes
Note I have not actually tried this with updating manifests, however based on reading the guide, it reads clear and easy to follow.  👍.

2023-11-30 21:08 UTC, mathewjordan commented on pages/enable-a-map-with-navPlace.mdx
> +    ...
Forget this.

2023-11-30 21:08 UTC, mathewjordan commented on pages/enable-a-map-with-navPlace.mdx
> +    ...
Forget this.

2023-11-30 21:09 UTC, mathewjordan commented on pages/enable-a-map-with-navPlace.mdx
> +    ...
Closed out my comments relating to the `...`.  So Ignore this.

2023-11-30 23:43 UTC, markpbaggett commented on pages/enable-a-map-with-navPlace.mdx
> +  1. Add the `navPlace` extension to the Linked Data Context of each manifest by adding
Would this be better:

```suggestion
  1. In accordance with the [specification](https://iiif.io/api/extension/navplace/#31-linked-data-context), Add the `navPlace` extension to the Linked Data Context of each manifest by adding
```

2023-12-01 16:08 UTC, mathewjordan commented on pages/enable-a-map-with-navPlace.mdx
> +  1. Add the `navPlace` extension to the Linked Data Context of each manifest by adding
Yeah, looks great. Replace `Add` with `include`?

2023-12-01 16:13 UTC, markpbaggett commented on pages/enable-a-map-with-navPlace.mdx
> +  }
```suggestion
[
  {
    "path": "/works",
    "text": "Works"
  },
  {
    "path": "/metadata",
    "text": "Metadata"
  },
  {
    "path": "/map",
    "text": "Map"
  },
  {
    "path": "/about",
    "text": "About"
  }
]
```

2023-12-01 16:17 UTC, mathewjordan commented on pages/enable-a-map-with-navPlace.mdx
> +  }
I wasn't very clear. Just replace with this and include the highlighting of the lines for the map entry.

```json copy
[
  {
    "path": "/works",
    "text": "Works"
  },
  {
    "path": "/metadata",
    "text": "Metadata"
  },
  {
    "path": "/map",
    "title": "Map"
  },
  {
    "path": "/about",
    "text": "About"
  }
]
```

2023-12-01 16:29 UTC, mathewjordan requested changes
Just one more thing.

2023-12-01 16:29 UTC, mathewjordan commented on pages/enable-a-map-with-navPlace.mdx
> +  ```json copy filename="content/_meta.json" {5}
```suggestion
  ```json copy filename="content/_meta.json" {10-13}
```

2023-12-01 16:39 UTC, merged