Create a Guide for StackBlitz
canopy-iiif/docs pull request #25
Opened 2023-12-01 21:07 UTC by adamjarling

First draft pass at a Guide/Documentation for running StackBlitz.  Maybe there's a better spot to highlight this?  Also not really sure how in depth to go here...  

Curious on your two cents @markpbaggett (not necessarily today as it's getting late), since this StackBlitz environment may be fresh/new to your eyes.

2023-12-02 13:16 UTC, markpbaggett requested changes
I stand by what I said previously, but just noticed this small error.

2023-12-02 13:16 UTC, markpbaggett commented on pages/stackblitz.mdx
> +```json file="/config/canopy.json" {19-20}
```suggestion
```json filename="/config/canopy.json" {19-20}
```

2023-12-02 20:25 UTC, adamjarling commented
@markpbaggett Committed your suggestion in the PR.  Thanks!

2023-12-03 12:34 UTC, mathewjordan commented on pages/get-started.mdx
> +[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz_small.svg)](https://stackblitz.com/fork/github/canopy-iiif/canopy-iiif?startScript=dev)
👍

2023-12-03 15:34 UTC, mathewjordan commented
Gonna merge this im so we can have the docs at a checkpoint.

2023-12-03 15:34 UTC, merged